version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - "./app:/myportfolio/app"
      - ./flask.sqlite:/myportfolio/flask.sqlite
